{% set name = "nionswift" %}
{% set version = "0.16.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #Use pypi for the next release, source distribution missing files
  #url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #sha256: 1f0aae216af499bf0c4e6e2571bd37d53ee75096866fa4266c9014d6d31fffb5
  url: https://github.com/nion-software/nionswift/archive/{{ version }}.tar.gz
  sha256: 4e7152cda7a41f161469c3c0ce795aeef91fd7bf718e97029987fd78dcfb594e

build:
  number: 0
  noarch: python
  entry_points:
    - nionswift=nion.swift.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - h5py
    - imageio >=2.19.0
    - niondata >=0.15.3,<0.16.0
    - nionswift-io >=0.15.0
    - nionui >=0.6.6,<0.7.0
    - nionutils >=0.4.5,<0.5.0
    - numpy >=1.21,<2.0
    - pillow
    - python >=3.8
    - pytz
    - scipy
    - tzlocal

test:
  imports:
    - nion.swift
    - nion.swift.model
    - nion.swift.test
    - nion.typeshed
    - nionlib
    - nionswift_plugin.none
    - nionui_app.nionswift

about:
  home: http://nion.com/swift
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Nion Swift: Scientific Image Processing'
  doc_url: https://nionswift.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/nion-software/nionswift

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
