{% set name = "nionswift" %}
{% set version = "16.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #Use pypi for the next release, source distribution missing files
  #url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #sha256: 1f0aae216af499bf0c4e6e2571bd37d53ee75096866fa4266c9014d6d31fffb5
  url: https://github.com/nion-software/nionswift/archive/{{ version }}.tar.gz
  sha256: 12471b6a4f547b7f2bec4ededa6c3da28784c95f88046cd67586a3650289d501

build:
  number: 0
  noarch: python
  entry_points:
    - nionswift=nion.swift.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - h5py
    - imageio >=2.19.0
    - niondata >=15.6.2,<16.0
    - nionswift-io >=15.2,<16.0
    - nionui >=7.0.2,<8.0
    - nionutils >=0.4.10,<5.0
    - numpy >=1.26,<2.0
    - pillow
    - python >=3.9
    - pytz
    - scipy
    - tzlocal

test:
  imports:
    - nion.swift
    - nion.swift.model
    - nion.swift.test
    - nion.typeshed
    - nionlib
    - nionswift_plugin.none
    - nionui_app.nionswift

about:
  home: http://nion.com/swift
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: 'Nion Swift: Scientific Image Processing'
  doc_url: https://nionswift.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/nion-software/nionswift

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
